### ISSUE TITLE
支持延迟消息统计

### ISSUE THREAD

**Issue by xujianhai666** [qunarcorp/qmq#107]
**问题描述**
有时候，需要知道 延迟服务中消息的总量，对业务做到透明。以及分发慢的时候，可以知道 lag 总量

**环境配置**

**复现步骤**
1.
2.
3.

**实际输出结果**

**期望输出结果**

**Comment by yuyijq** [comment]
@xujianhai666 
为啥要关注消息总量？
我们实际运维中，对于延时消息我们一般关注 消息实际投递时间与期望投递时间之差，delayTime 这个监控指标
