### ISSUE TITLE
有些问题想咨询下QMQ团队

### ISSUE THREAD

**Issue by Xiecai** [qunarcorp/qmq#114]
各位好，参看QMQ的架构概览有些疑问想请教下

1. 关于实时消息的设计，我的理解是首先所有的消息都是顺序写到message log，consume log是记录关于某一个主题的在message log上的索引位置以示区分。这层中间件的概念我理解了。文中“_**pull log方框内的内容对应着consume log的逻辑偏移**_”。这里要是一个消费者只关心一个主题还可以，但是存在一个消费者订阅多个主题的情况，这里就有些疑问。这里看pull log只记录了consume log的索引位置，还是说pull log里的消息除了记consume log的索引位置，同时还记录着是哪个主题下的吗？作为消费者是只关心一个pull log就可以了吗？还是说会一个消费者在拉取的时候，拉取多个pull log？

2. “_**消费者就可以使用pull log上的sequence来表示消费进度**_”各消费组消费同一个消息的进度可能不同，那么这里如何判断一个消息彻底被所有组都消费完了呢？是否需要所有组确认消费完成呢？还是说无需关心各消费组的情况，待消息的过期时间到了自行删除？

3. 一个消息会存在于message log，同时其索引位置会在consume log，按设计也会把consume log的索引位置存在于pull log，那么当一个消息彻底结束后，pull log与consume log什么时候将关于这条消息记录清除呢？

4. 设计背景中阐述，qmq对于扩容及缩容方便处理，对于处理堆积于单一队列的数据也能很好处理。这里看，消费者只关心pull log，那么扩容是怎么搞的呢？多个pull log？那么如果消息都堆积在pull log，如何横向扩展呢，没太看明白？

大佬有时间给解惑下

**Comment by keliwang** [comment]
1. pull log 并不是一个 consumer 只有一个，而是每个主题下的每个消费组的每个 consumer 都会创建一个 pull log。即一个 consumer 可以有很多个 pull log。
2. 消息目前是消息过期自行删除的。
3. 目前每种 log 都是按照过期时间来判断是否需要删除的。
4. pull log 是 consumer 拉取消息时根据实际拿到了哪些消息而生成的拉取记录，不存在拉取堆积的问题。拉取堆积只会发生在 consumer log 这一层。

**Comment by Xiecai** [comment]
明白了

**Comment by Xiecai** [comment]
感谢
