### ISSUE TITLE
如果我想查询消息队列中，还未被消费堆积的消息，应该如何去做呢

### ISSUE THREAD

**Issue by ToTouchMyheart** [qunarcorp/qmq#133]
**问题描述**
目前的话只找到了prometheus下提供的监控堆积消息数量的接口，如果想查看具体的堆积消息信息应该如何去做呢。
目前开源的QMQ是不是没有提供管理界面的功能呢？
望解答 谢谢

**Comment by keliwang** [comment]
目前没有管理界面，也没有查看具体堆积消息的好办法。一个方法是通过 qmq-backup 将消息备份，然后通过查看备份可以知道哪些消息没有被消费。

**Comment by ToTouchMyheart** [comment]
好的谢谢啦。还有就是 我没有生产很多消息 为什么/data/messageLog这个文件就几个G了呢 是不是有地方配置错了

**Comment by ToTouchMyheart** [comment]
好的谢谢啦。还有就是 我没有生产很多消息 为什么/data/messageLog这个文件就几个G了呢 是不是有地方配置错了

**Comment by keliwang** [comment]
这些数据文件目前是预分配空间的，所以初始空间占用看着比较大。
