### ISSUE TITLE
broker 启动异常

### ISSUE THREAD

**Issue by ToTouchMyheart** [qunarcorp/qmq#134]
**问题描述**
由于v1.1.3.5不支持backup server，所以将master的代码重新编译使用。在启动broker的时候 出现异常

**环境配置**

**复现步骤**
**实际输出结果**
![image](https://user-images.githubusercontent.com/22099172/120601996-22478280-c47d-11eb-9593-505d71f99da5.png)

另：
![image](https://user-images.githubusercontent.com/22099172/120602055-37bcac80-c47d-11eb-979d-adaff2711fcf.png)
也会出现空指针异常，是不是缺少某些地方的配置呢？
**期望输出结果**

**Comment by keliwang** [comment]
metaserver 上注册这台 broker 了么？可以看看 metaserver 的日志。

**Comment by ToTouchMyheart** [comment]
metaserver上已经注册了，数据库里面broker的表里面是有这条数据的 
metaserver也是正常启动的 不过会一直报这个的空指针
![image](https://user-images.githubusercontent.com/22099172/120605260-70aa5080-c480-11eb-9f5b-7c76090fb231.png)

**Comment by ToTouchMyheart** [comment]
看样子好像都是监控那边的有问题呢

**Comment by keliwang** [comment]
这个异常看着是没有 broker 信息，metaserver 库的 broker_group 表里有数据么？

**Comment by ToTouchMyheart** [comment]
broker_group 这个表里面没有值。但是我之前是1.1.3.5的时候 这个表里的数据是在启动broker之后才会加进去的吧

**Comment by keliwang** [comment]
参考 https://github.com/qunarcorp/qmq/blob/master/docs/cn/install.md#%E5%90%AF%E5%8A%A8-6 这里，broker 启动前要先在 metaserver 上注册。

**Comment by ToTouchMyheart** [comment]
我已经注册过了，注册的话 只会往broker的表里面添加数据吧，broker_group应该是在注册过后，启动broker之后 才会添加数据吧

**Comment by keliwang** [comment]
看了下，我记错了，抱歉。那你看看 broker 启动之后 metaserver 有没有 broker 相关的日志，metaserver 收到请求会输出日志的。

**Comment by ToTouchMyheart** [comment]
找到问题了。。
1.初始化了一遍数据库的表，但是忘记停止broker了。
2.启动metaserver ，并注册broker
3.broker这个表里面会添加一条数据，但是broker_group这个表里面并没有添加
4.停止broker 再重新启动 就会有这个问题 。。

不好意思 这应该算是我的操作失误 。。。麻烦了
