### ISSUE TITLE
dead_backup.properties这个文件可以上传一下么 在代码中没找到

### ISSUE THREAD

**Issue by ToTouchMyheart** [qunarcorp/qmq#135]
**问题描述**

**环境配置**

**复现步骤**
1.
2.
3.

**实际输出结果**

**期望输出结果**

**Comment by keliwang** [comment]
我加到 https://github.com/qunarcorp/qmq/blob/master/docs/cn/install.md#%E9%85%8D%E7%BD%AE%E6%96%87%E4%BB%B6-4 这里了，你试试。
