### ISSUE TITLE
请教下consumer扩容的问题

### ISSUE THREAD

**Issue by jinhaojie** [qunarcorp/qmq#156]
**问题描述**
看了qmq的设计文档，qmq能够动态扩容一个主题内的consumer，而rocketMq,kafka等受分区或者队列数量的限制不能做到consumer大于分区的数量。想问下既然qmq可以做到，为什么kafka，rocketmq没有去做？这其中的考量是什么？

**环境配置**

**复现步骤**
1.
2.
3.

**实际输出结果**

**期望输出结果**

**Comment by keliwang** [comment]
支持 consumer 扩容需要额外维护消息和 consumer 直接的映射关系，处理消费进度的逻辑会更复杂。可以参考 https://www.splunk.com/en_us/blog/it/comparing-pulsar-and-kafka-unified-queuing-and-streaming.html ，实际上是两种不同的模式。

**Comment by jinhaojie** [comment]
了解了，谢谢大佬解答
