### ISSUE TITLE
consumer group是如何分配由哪一台机器拉取消息

### ISSUE THREAD

**Issue by ymliangz** [qunarcorp/qmq#37]
看到文档说，消费端都是一个拉取循环，服务端维护一个request队列，哪是如何决定group里面只有一台机器消费了消息呢。是消费端的一个group的所有机器都会请求服务端，由服务端通过负载均衡决定向哪个消费机器响应吗

**Comment by yuyijq** [comment]
消费端的一个group的所有机器都会请求服务端，由服务端通过负载均衡决定向哪个消费机器响应
