### ISSUE TITLE
ubuntu环境，启动脚本不兼容

### ISSUE THREAD

**Issue by njkfei** [qunarcorp/qmq#39]
**问题描述**
ubuntu环境下，
```
sh +x metaserver.sh start
```

报错：
```
root@ubuntu:/data/qmq_dist/qmq-dist-1.1.3.3-bin/bin# sh +x metaserver.sh start
metaserver.sh: 2: set: Illegal option -o pipefail
```

**环境配置**
ubuntu

**复现步骤**
1.
2.
3.

**实际输出结果**

**期望输出结果**

**原因**
ubuntu的 shell 默认安装的是 dash，而不是 bash。

**解决方案**
```
$sudo dpkg-reconfigure dash
```
然后选择 no 或者 否 ，并确认。
这样做将重新配置 dash，并使其不作为默认的 shell 工具。

参考：https://blog.csdn.net/sahusoft/article/details/9115367

**Comment by yuyijq** [comment]
Thanks, I will add this to doc
