### ISSUE TITLE
服务器配置了metaserver，为什么还要手动注册？

### ISSUE THREAD

**Issue by sundylgz** [qunarcorp/qmq#40]
服务器配置了metaserver，为什么还要手动注册？

**Comment by yuyijq** [comment]
qmq的生产推荐配置是一主一从成为一个group，每个group需要配置一个group name(全局唯一)，所以我们需要指定：group name和主从关系。当然这些也可以放在配置文件里然后server启动后自动向metaserver注册，但是这样一来不同的server的配置文件就需要不一样(需要指定group name和主从关系)

不同server配置不同并不利于自动化部署，qmq的手动注册过程相当于将配置外置，这样所有server的配置都是一样的了。

**Comment by sundylgz** [comment]
明白，你们是想在运维角度配置文件一样，然后通过手动指定来配置管理
