### ISSUE TITLE
部分代码日志打印格式化问题

### ISSUE THREAD

**Issue by ex34toway** [qunarcorp/qmq#41]
**问题描述**
部分代码日志打印问题

**复现步骤**
        LOGGER.debug("NettyConnectManageHandler", "NETTY CLIENT PIPELINE: DISCONNECT {}", remoteAddress);
        LOGGER.debug("NettyConnectManageHandler", "NETTY CLIENT PIPELINE: CLOSE {}", remoteAddress);

**实际输出结果**
NettyConnectManageHandler
NettyConnectManageHandler

**期望输出结果**
NETTY CLIENT PIPELINE: DISCONNECT 192.168.11.29
NETTY CLIENT PIPELINE: CLOSE 192.168.11.29

**Comment by keliwang** [comment]
多谢反馈，我修一下。

**Comment by keliwang** [comment]
已修复
