### ISSUE TITLE
分布式事务如何控制的？

### ISSUE THREAD

**Issue by zjg23** [qunarcorp/qmq#42]
请问下图中server处理失败，producer是怎么处理的？有单独的分布式事务控制组件么？
https://github.com/qunarcorp/qmq/blob/master/docs/cn/transaction.md
![image](https://user-images.githubusercontent.com/12578973/53628061-01ac7480-3c45-11e9-854b-cbc29849e3a7.png)

**Comment by yuyijq** [comment]
如果producer发送server失败，那么消息就会留在本地的消息表里，右下角有一个task服务，会不断地将留在消息表里的消息扫出来重发，直到发送成功，达到最终一致性。
