### ISSUE TITLE
一个关于延时消息的load小问题，以及可能的多线程问题

### ISSUE THREAD

**Issue by Ah39** [qunarcorp/qmq#44]
https://github.com/qunarcorp/qmq/blob/d74b66a5d7fc07db12bc5f48a20aee0b022d94e1/qmq-delay-server/src/main/java/qunar/tc/qmq/delay/wheel/WheelTickManager.java#L290-L301
我的理解是：当前的时间段的消息会实时加入时间轮，load任务offset 之后的下一个时间片的消息，会实时加入时间轮
延时消息当前时间片段要到期的时候，是怎么load下一个时间段的。如果是定时load，比如每分钟跑一次，加入17:59:00 这个load定时任务运行过了，在17:59:00之后，写入了18:00-19:00的消息，这些消息怎么load上来。
load任务怎么保证消息索引不漏和不重复地加入时间轮

**Comment by yuyijq** [comment]
```java
    //根据消息的延时时间(scheduleTime)，计算该消息应该落在schedule log的哪个分片(segment)
    long baseOffset = resolveSegment(scheduleTime, segmentScale); 
     //如果该分片的偏移比当前正在投递的分片偏移小，则立即添加进内存时间轮
     if (baseOffset < currentBaseOffset) return true; 
      
     //如果该消息正好需要落在当前时间片
     if (baseOffset == currentBaseOffset) {
         //则判断该消息在当前schedule log segment里的偏移是否大于正在加载的最大偏移，如果大的话则立即加载到内存时间轮。这里要注意的是，当加载任务决定要加载某个segment的时候，就会立即固定住当时该segment的最大偏移，也就是currentOffset，所以这样就不会将消息重复的加载 
         return currentOffset <= offset; 
     } 
```

**Comment by Ah39** [comment]
这个里面，多线程好像会有问题
https://github.com/qunarcorp/qmq/blob/d74b66a5d7fc07db12bc5f48a20aee0b022d94e1/qmq-delay-server/src/main/java/qunar/tc/qmq/delay/wheel/WheelTickManager.java#L292-L293
在第一行如果是获取到的是比如，2019040219这个小时是baseOffset，如果在极端情况下
假如2019040219 的offset为1500，2019040220这个小时的写入offset为1600
 在执行第二句代码的时候，load任务改成了2019040220，offset变成了1600，第二行获取到的就是1600,
     long currentOffset = currentCursor.getOffset(); 
会导致有些消息索引，没有写入时间轮

**Comment by yuyijq** [comment]
@Ah39 

不会的

```java
      // 这里的loadingCursor.cursor() 是返回的一个新实例的，所以currentCursor只在当前线程可见的，别的线程不会修改它的
       WheelLoadCursor.Cursor currentCursor = loadingCursor.cursor();
        int currentBaseOffset = currentCursor.getBaseOffset();
        long currentOffset = currentCursor.getOffset();
```

**Comment by Ah39** [comment]
恩恩，是一个新实例，确实不会有多线程问题
