### ISSUE TITLE
RetryTask好像逻辑有点问题，当前commit 7b7b456

### ISSUE THREAD

**Issue by fankaidev** [qunarcorp/qmq#50]
**问题描述**

当一个consumer进入离线(offline)状态之后，会触发一个RetryTask, 其逻辑应当是：
1. 比较该consumerId的firstNotAckedSequence和lastPulledSequence，如果lastPulledSequence < firstNotAckedSequence, 说明该consumer所有pull的消息都已经处理完毕，无须retry
2. 否则，需要把所有未处理完成的消息放入retry queue中，并手动ack原来的消息

这部分逻辑是在RetryTask.run()函数中执行，其中第一步应该是在processSkipRetry()中执行。
`        if (processSkipRetry(consumerSequence)) return;
`

但是看代码，发现两个问题
1.  在processSkipRetry()这个函数中所有的路径都会返回true，导致第2步里的逻辑不会得到执行。
```
    private boolean processSkipRetry(ConsumerSequence consumerSequence) {
        if (!consumerSequence.tryLock()) return true;
        try {
            final long firstNotAckedSequence = consumerSequence.getAckSequence() + 1;
            final long lastPulledSequence = consumerSequence.getPullSequence();
            if (lastPulledSequence < firstNotAckedSequence) return true;

            // put ack action
           ...
        } finally {
            consumerSequence.unlock();
        }
        return true;
    }
```
2. 在这个函数内外都手动执行了对于未处理消息的ack，感觉是重复了

**环境配置**

**复现步骤**
1. 只需要一个consumer消费的比较慢，(比如在这个[commit](https://github.com/fankaidev/qmq/commit/020a3b7b0c7a7789811fb12a07c09012e5fbd5ce)里我改了一下qmq-demo)，手动kill consumer就可以容易的复现

**实际输出结果**
consumer崩溃之后，当前未ack的消息不会被处理

**期望输出结果**
consumer崩溃之后，当前未ack的消息会被加入retry queue并重新处理

**Comment by yuyijq** [comment]
额，是开源的时候删掉了一个配置项

这个skip的原本的作用是有一个动态开关，人工可以干预，在某些时候对某些消息配置不重发。该功能需要和配置中心配合，所以开源的时候删掉了，但是对应逻辑忘记删了..

非常感谢，我已经修改了
