### ISSUE TITLE
能再详细介绍下如何通过dispatch log避免重复投递吗？

### ISSUE THREAD

**Issue by wangcn** [qunarcorp/qmq#58]
dispatch log 延时/定时消息投递成功后写入，主要用于在应用重启后能够确定哪些消息已经投递，dispatch log里写入的是消息的offset，不包含消息内容。当延时server中途重启时，我们需要判断出当前这个刻度(比如一个小时)里的消息有哪些已经投递了则不重复投递。

这段不是太明白。比如下一小时的msg已经load到内存了，此时宕机，怎么知道哪些消息已经投递了？

**Comment by yuyijq** [comment]
上面那段话就解释了啊：
在延时消息投递成功后写入dispatch log，如果中途重启了，再启动的时候那我就可以加载dispatch log，看看已经在dispatch log的就不再重复投递了

**Comment by wangcn** [comment]
是将整个dispatch log加载到内存，然后再读取schedule log并检查消息是否在dispatch log里？

**Comment by yuyijq** [comment]
对，将dispatch log加载到内存，dispatch log只有offset，整个加载到内存也没多大

**Comment by wangcn** [comment]
是以什么结构放在内存中的？

**Comment by yuyijq** [comment]
https://github.com/qunarcorp/qmq/blob/master/qmq-delay-server/src/main/java/qunar/tc/qmq/delay/base/LongHashSet.java

**Comment by wangcn** [comment]
非常感谢。能否出一个文档，描述一下工程中的最佳实践，比如这种数据结构以及重启后快速定位数据起点之类的？
