### ISSUE TITLE
开源版与内部使用版是否一致？

### ISSUE THREAD

**Issue by liangyuanpeng** [qunarcorp/qmq#9]
**问题描述**
开源版与内部使用版是否一致？

**环境配置**

**复现步骤**
1.
2.
3.

**实际输出结果**

**期望输出结果**

**Comment by keliwang** [comment]
核心的功能是一致的，有些和内部系统耦合比较多的部分不一致。包括：
1. 配置文件载入、监控、Trace使用了内部未开源的系统，开源时用目前使用比较广泛的对应组件做了替代。
2. 暂时缺少了事务消息、管理界面这些和内部系统耦合比较多的部分，需要进一步处理。
