### ISSUE TITLE
单机(本机)启动 metaserver，server，delay三个服务，然后会看到 delay 和server 注册有问题

### ISSUE THREAD

**Issue by Ants2GitHub** [qunarcorp/qmq#96]
**问题描述**
如题。 本机启动三个服务，然后测试发送消息以及消费消息，在启动server之后 再去启动delay，发现注册组会有问题，查看是区分时 按照hostname 和端口 确定为唯一的，这种有完整的单机(或idea)启动全部服务的文档么。

有没有微信交流群什么的呢？ QQ交流群 加群都没加上。

**环境配置**

**复现步骤**
1.
2.
3.

**实际输出结果**

**期望输出结果**
希望 能给到完整的本地(单机)部署文档

谢谢。

**Comment by yuyijq** [comment]
@Ants2GitHub 单机部署文档和集群部署文档就是一样的，端口冲突肯定不行啊

微信群超过200人要邀请才能加入，你可以先加入qq群，qq群是可以加的
